apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: datadog-agent
spec:
  selector:
    matchLabels:
      app: datadog-agent
  template:
    metadata:
      labels:
        app: datadog-agent
      name: datadog-agent
    spec:
      hostNetwork: true
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      serviceAccountName: datadog-agent
      containers:
      - image: datadog/agent:7
        imagePullPolicy: Always
        name: datadog-agent
        ports:
          - containerPort: 8125
            # Custom metrics via DogStatsD - uncomment this section to enable custom metrics collection
            # hostPort: 8125
            name: dogstatsdport
            protocol: UDP
          - containerPort: 8126
            # Trace Collection (APM) - uncomment this section to enable APM
            # hostPort: 8126
            name: traceport
            protocol: TCP
        env:
          - name: DD_LOG_LEVEL
            value: "debug"
          - name: DD_API_KEY
            valueFrom:
              secretKeyRef:
                name: datadog-secret
                key: api-key
          - name: DD_COLLECT_KUBERNETES_EVENTS
            value: "true"
          - name: DD_LEADER_ELECTION
            value: "true"
          - name: KUBERNETES
            value: "true"
          - name: DD_HEALTH_PORT
            value: "5555"
          - name: DD_KUBERNETES_KUBELET_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: DD_APM_ENABLED
            value: "true"
          - name: DD_LOGS_ENABLED
            value: "true"
          - name: DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL
            value: "true"
          - name: DD_AC_EXCLUDE
            value: "name:datadog-agent"
          - name: DD_LOGS_CONFIG_K8S_CONTAINER_USE_FILE
            value: "true"
          - name: DD_LOGS_CONFIG_USE_HTTP
            value: "true"
          - name: DD_LOGS_CONFIG_USE_COMPRESSION
            value: "true"
          - name: DD_LOGS_CONFIG_COMPRESSION_LEVEL
            value: "6"
          - name: DD_PROCESS_AGENT_ENABLED
            value: "true"
          - name:  DD_KUBELET_TLS_VERIFY
            value: "false"
          - name: DD_CRI_SOCKET_PATH
            value: "/var/run/crio/crio.sock"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
          - name: pointdir
            mountPath: /opt/datadog-agent/run
          - name: procdir
            mountPath: /host/proc
            readOnly: true
          - name: cgroups
            mountPath: /host/sys/fs/cgroup
            readOnly: true
          - name: var-run
            mountPath: /host/var/run
            readOnly: true
          - name: logpodpath
            mountPath: /var/log/pods
          - name: logcontainerpath
            mountPath: /var/lib/docker/containers
          - name: criosocket
            mountPath: /var/run/crio/crio.sock
          - name: empty-dir
            mountPath: /var/run/s6
          - name: empty-dir
            mountPath: /etc/datadog-agent/conf.d/docker.d
          - name: datadog-agent-config
            mountPath: /conf.d
          - name: datadog-agent-config-crio
            mountPath: /etc/datadog-agent/conf.d/cri.d
        livenessProbe:
          httpGet:
            path: /health
            port: 5555
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      volumes:
        - hostPath:
            path: /proc
          name: procdir
        - hostPath:
            path: /sys/fs/cgroup
          name: cgroups
        - hostPath:
            path: /var/run
            type: DirectoryOrCreate
          name: var-run
        - hostPath:
            path: /opt/datadog-agent/run
          name: pointdir
        - hostPath:
            path: /var/log/pods
          name: logpodpath
        - hostPath:
            path: /var/lib/docker/containers
          name: logcontainerpath
        - hostPath:
            path: /var/run/crio/crio.sock
          name: criosocket
        - name: empty-dir
          emptyDir: {}
        - name: datadog-agent-config
          configMap:
            name: datadog-agent-config
        - name: datadog-agent-config-crio
          configMap:
            name: datadog-agent-config-crio
            items:
            - key: cri
              path: conf.yaml
