kind: ConfigMap
apiVersion: v1
metadata:
  name: datadog-agent-config
  namespace: datadog-agent
data:
  kubernetes_state: |-
    ad_identifiers:
      - ocp-v4.0-art-dev
    init_config:
    ignore_autodiscovery_tags: true
    instances:
      - kube_state_url: http://%%host%%:8080/metrics
